[general]
import = [
    "~/.config/alacritty/themes/customized_gnome.toml"
]
live_config_reload = true

[window]
padding = { x = 2, y = 10 }

[font]
size = 11

[font.bold]
family = "SourceCodeVF"
style = "Bold"

[font.bold_italic]
family = "SourceCodeVF"
style = "Bold Italic"

[font.italic]
family = "SourceCodeVF"
style = "Italic"

[font.normal]
family = "SourceCodeVF"
style = "Regular"